### ISSUE TITLE
this is for scope?

### ISSUE THREAD

**Issue by Phoenix1112** [ghsec/webHunt#1]
hello. this is for scope ? 
(http[s]?:\/\/)?((-)?[\w+\.])+{7}domain\.com

**Comment by ghsec** [comment]
Yes. And you can use this in search function in burp

**Comment by Phoenix1112** [comment]
Thank you. Have you twitter address for follow

**Comment by ghsec** [comment]
Yes. @GochaOqradze

Check out გოჩა ოქრაძე (Gocha Okradze) (@GochaOqradze): https://twitter.com/GochaOqradze?s=09

**Comment by Phoenix1112** [comment]
ok.. i did follow you on twitter..
